name: Deploy TIBR Screen

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      # 1. Checkout latest code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 4. Build project
      - name: Build Project
        run: npm run build
        env:
          VITE_APP_URL: ${{ secrets.VITE_APP_URL }}
          VITE_APP_API_KEY: ${{ secrets.VITE_APP_API_KEY }}
          VITE_APP_ADMIN_ID: ${{ secrets.VITE_APP_ADMIN_ID }}
          VITE_APP_SOCKET_SECRET_KEY: ${{ secrets.VITE_APP_SOCKET_SECRET_KEY }}

      # 5. Prepare TIBR folder
      - name: Prepare TIBR folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/html/TV_Screens/TIBR/*
            sudo mkdir -p /var/www/html/TV_Screens/TIBR
            sudo chown -R ubuntu:ubuntu /var/www/html/TV_Screens/TIBR

      # 6. Upload new build
      - name: Upload Build Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/html/TV_Screens/TIBR"
          strip_components: 1
          overwrite: true

      # 7. Fix permissions
      - name: Set Permissions
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo find /var/www/html/TV_Screens/TIBR -type d -exec chmod 755 {} \;
            sudo find /var/www/html/TV_Screens/TIBR -type f -exec chmod 644 {} \;

      # 8. Verify Nginx configuration
      - name: Verify Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo nginx -t

      # 9. Reload Nginx
      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl reload nginx